application: choosewithalice
version: 1
runtime: php55
api_version: 1

handlers:

- url: /assets
  static_dir: public/assets

- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public/favicon\.ico

- url: /robots\.txt
  static_files: public/robots.txt
  upload: public/robots\.txt

- url: /
  static_files: public/index.html
  upload: public/index\.html

- url: /app
  static_files: public/app.html
  upload: public/app\.html
