application: choosewithalice
version: 1
runtime: php55
api_version: 1

handlers:

- url: /assets/js/alice\.js
  script: alice.js.php

- url: /assets
  static_dir: public/assets



- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public/favicon\.ico

- url: /robots\.txt
  static_files: public/robots.txt
  upload: public/robots\.txt

- url: /
  static_files: public/index.html
  upload: public/index\.html

- url: /list
  static_files: public/list.html
  upload: public/list\.html

- url: /comparison
  static_files: public/comparison.html
  upload: public/comparison\.html

- url: /kyc
  static_files: public/kyc.html
  upload: public/kyc\.html
